# Utilisez l'image de base officielle de Python
FROM python:3.12

WORKDIR /app

COPY ../../requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY fastapi_app.py .
COPY ./models /app/models

EXPOSE 8000

CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]