FROM python:3.8-slim

WORKDIR /app

COPY ../../requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY fastapi_app.py .
COPY ../model /app/model

EXPOSE 8000

CMD ["uvicorn", "fastapi_app:app", "--host", "localhost", "--port", "8000"]
